name: qaswa_user
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  velocity_x: ^3.6.0
  get: ^4.6.5
  cloud_firestore: ^4.3.0
  firebase_auth: ^4.2.3
  image_picker: ^0.8.6
  firebase_storage: ^11.0.9
  path: ^1.8.2
  mime_type: ^1.0.0
  badges: ^3.0.2
  cached_network_image: ^3.2.3
  validation_textformfield: ^2.2.5
  get_storage: ^2.0.3
  flutter_launcher_icons: ^0.11.0
  concentric_transition: ^1.0.3
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  background_color: "0xFF1A237E"
  image_path: "assets/icons/darklogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - lib/services/category_model.json

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf
    
    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf

